name: Generate File From OpenAI

on:
  workflow_call:
    inputs:
      outPath:
        required: true
        type: string
      systemPrompt:
        required: true
        type: string
      userPrompt:
        required: true
        type: string
      temperature:
        required: false
        type: string
        default: "0.5"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate content
        id: chat
        uses: Just-Moh-it/openai@v0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-mode: chat
          openai-params: |
            {
              "model": "gpt-4o",
              "temperature": ${{ inputs.temperature }},
              "messages": [
                {"role": "system", "content": "${{ inputs.systemPrompt }}" },
                {"role": "user", "content": "${{ inputs.userPrompt }}" }
              ]
            }

      - name: Save to file
        run: |
          mkdir -p $(dirname "${{ inputs.outPath }}")
          echo "${{ steps.chat.outputs.text }}" > "${{ inputs.outPath }}"

      - name: Commit output file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add "${{ inputs.outPath }}"
          git commit -m "Generate ${{ inputs.outPath }}"
          git push
