// AI Game Generator - Procedural game generation using AI
// Copyright (C) 2024 AI Game Generator Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the MIT License as published by
// the Open Source Initiative.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

// Generated by metaprompt-runner-v2
// Source: game-config.yaml
// Template: src/tilemaps/mod

pub mod verdant_flats;
pub mod glintrock_expanse;
pub mod cratervine_chasm;
pub mod ashbarrow_wastes;
pub mod forgotten_roots;
