#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged for formatting and linting
npx lint-staged

# Run affected tests
npm run test:affected

# Validate affected code
npm run lint:affected